import "@/app/globals.css";
import { Footer, Header } from "@/components";
import ThemeProvider from "@/components/atoms/ThemeProvider";
import type { Metadata } from "next";
import { Sarabun, Tajawal } from "next/font/google";


import localFont from "next/font/local";

const sarabun = localFont({
  src: [
    {
      path: "/fonts/Sarabun/Sarabun-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/Sarabun/Sarabun-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-sarabun",
});

const tajawal = localFont({
  src: [
    {
      path: "/fonts/Tajawal/Tajawal-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/Tajawal/Tajawal-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-tajawal",
});


// const sarabun = Sarabun({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700", "800"],
//   variable: "--font-sarabun",
// });
// const tajawal = Tajawal({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "700", "800"],
//   variable: "--font-tajawal",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${sarabun.variable} ${tajawal.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <main className="mx-20 mt-10">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
